services:
  front-end:
    image: alasso:dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll=2000 --disable-host-check

  # angular-dev:
  #   image: 'angular-dev'
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #   - "4200:4200"
  #   develop:
  #     watch:
  #       - action: sync
  #         path: .
  #         target: /app


