FROM node:alpine AS build
WORKDIR /app
ARG MAP_API_KEY
COPY package.json ./
RUN npm install
COPY . ./
RUN echo "$MAP_API_KEY" > src/environments/environment.secret.ts
RUN npm run build:staging

FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/frontend/browser ./
EXPOSE 80