services:
  alasso-frontend-production:
    image: alasso/alasso-frontend:production
    container_name: alasso-frontend-production
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alasso-frontend-production.rule=Host(`a-l-asso.fr`)"
      - "traefik.http.routers.alasso-frontend-production.entrypoints=websecure"
      - "traefik.http.routers.alasso-frontend-production.tls.certresolver=letsencrypt"
      - "traefik.http.services.alasso-frontend-production.loadbalancer.server.port=80"

networks:
  traefik:
    external: true